# Generated by Django 3.2.9 on 2021-11-17 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='created', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='False if an admin has removed this approver')),
                ('mute_comments', models.BooleanField(default=False, help_text='True if an approver has chosen to not receive new comments via email')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_notified_time', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='The person who added this approver. Null if user was in approval policy', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
